### ISSUE TITLE
Referring to contents of lists

### ISSUE THREAD

**Issue by Jadelette** [Jadelette/Jade-s-Stuff#2]
Hiya!! 

How do I refer to the actual value of the object in a list (rather than it's index number)? Is it stored somewhere with a variable name?.. I feel like I'm missing something obvious!

Hopefully you get what I'm on about/trying to do from the below example: 

import java.util.ArrayList;

public class Temperatures {
	
	public static void main(String[] args) {
    
    ArrayList<Integer> weeklyTemperatures = new ArrayList<Integer>();
    
    weeklyTemperatures.add(78);
    weeklyTemperatures.add(67);
    weeklyTemperatures.add(89);
    weeklyTemperatures.add(94);
    
    int lowestTemp = **_[value associated with index position 0]_**;
    
    for (int counter = 1; counter < weeklyTemperatures.size(); counter++){
      
      if (lowestTemp > **[value associated with index number]**){
        lowestTemp = **_[value associated with index number]_**;
      } 
    }
    
    System.out.println(lowestTemp);
	}
}

Does this make sense, and is it possible to refer to the value of the indexed object? If not, how else could I make it work out the lowest value in the list? 

Sorry if it's a dumb question!... at least I'm working on something though!! :) 

J

**Comment by Jadelette** [comment]
Nevermind - I figured out I was over-complicating it! Got it working as below! :)

import java.util.ArrayList;

public class TemperaturesC {

    public static void main(String[] args) {

        ArrayList<Integer> weeklyTemperatures = new ArrayList<Integer>();
        weeklyTemperatures.add(78);
        weeklyTemperatures.add(67);
        weeklyTemperatures.add(89);
        weeklyTemperatures.add(94);

        int lowestTemp = weeklyTemperatures.get(0);

        for (int i = 1; i < weeklyTemperatures.size(); i++){

            int  compareTemp = weeklyTemperatures.get(i);

            if (compareTemp < lowestTemp) {

                lowestTemp = compareTemp;
            }
        }

        System.out.println(lowestTemp);

**Comment by Jadelette** [comment]
Apparently just asking questions helps me figure them out! haha! 

I'll find something harder to ask about next time! :p

**Comment by timpharo** [comment]
Tbh i just saw this now. What you referred to above however is called 'rubber ducking' (https://en.m.wikipedia.org/wiki/Rubber_duck_debugging). In general in programming, just talking someone else through the issue helps

**Comment by timpharo** [comment]
In general you should most probably prefer the forEach loop as it is less prone to errors.  The other for loop is worth understanding as there will be times that you don't only want the element out of the list but you also need the index for something else.  

It does seem like you have committed everything so thats great, we can look at how to use pull request later as another exercise as at this stage i think that it is more important to learn the language and and reasoning behind things instead of diving to far into the tooling.

As always give me a shout whenever, especially if the duckies aren't making much sense 👍
